#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.5"

module OS
    def OS.windows?
        (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    end

    def OS.mac?
        (/darwin/ =~ RUBY_PLATFORM) != nil
    end

    def OS.unix?
        !OS.windows?
    end

    def OS.linux?
        OS.unix? and not OS.mac?
    end
end

# Check to determine whether we're on a windows or linux/os-x host,
# later on we use this to launch ansible in the supported way
# source: https://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby
def which(cmd)
    exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
    ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
        exts.each { |ext|
            exe = File.join(path, "#{cmd}#{ext}")
            return exe if File.executable? exe
        }
    end
    return nil
end
Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = "adloginpoc"
        v.customize [
            "modifyvm", :id,
            "--name", "adloginpoc",
            "--memory", 2048,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
        ]
    end

    config.vm.box = "bento/ubuntu-16.04"
    
    config.vm.network :private_network, ip: "192.168.33.99"
    config.ssh.forward_agent = true

    config.vm.synced_folder ".", "/vagrant", disabled: true

    if OS.mac?
       config.vm.synced_folder "../php/adloginpoc", "/var/www/adloginpoc", id: "workspace", type: "nfs"
       config.vm.synced_folder "../ansible", "/ansible", id: "ansible", type: "nfs"
    elsif OS.linux?
       config.vm.synced_folder "../php/adloginpoc", "/var/www/adloginpoc", id: "workspace", type: "nfs"
       config.vm.synced_folder "../ansible", "/ansible", id: "ansible", type: "nfs"
    elsif OS.windows?
       config.vm.synced_folder "../php/adloginpoc", "/var/www/adloginpoc", id: "workspace", type: "smb", mount_options: ["mfsymlinks,dir_mode=0775,file_mode=0775"]
       config.vm.synced_folder "../ansible", "/ansible", id: "ansible", type: "smb", mount_options: ["mfsymlinks,dir_mode=0775,file_mode=0775"]
    end

    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################

    
    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/ansible"
        ansible.playbook = "/ansible/vagrant-playbook.yml"
        ansible.extra_vars = {
            private_interface: "192.168.33.99",
            hostname: "adloginpoc"
        }
    end
end
