---

- name: Add PostgreSQL Repository
  become: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present

- name: Add Keys for PostgreSQL Repository
  become: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install PostgreSQL Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql-9.5
    - postgresql-client-9.5
    - python-pygresql
    - python-psycopg2

- name: Create databases
  become: yes
  become_user: postgres
  postgresql_db: name={{ pgsql.database }} state=present

- name: Create users
  become: yes
  become_user: postgres
  postgresql_user: name={{ pgsql.user }} password={{ pgsql.password }} db={{ pgsql.database }} priv=ALL

- name: Install PostGIS
  become: yes
  apt: pkg=postgis state=latest

- name: Template sql script
  template:  src="init-postgis.sql.tpl" dest="/tmp/init-postgis.sql"

- name: Execute sql script
  become: yes
  become_user: postgres
  shell: "psql -f /tmp/init-postgis.sql {{ pgsql.database }}"

- name: Delete sql script
  file: path="/tmp/init-postgis.sql" state=absent
