- name: Install php7.2-fpm
  become: yes
  apt: pkg=php7.2-fpm state=latest

#Needed for PHP 5.4
#- name: Set permissions on socket - owner
#  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = www-data'"

#- name: Set permissions on socket - group
#  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.group' line='listen.group = www-data'"

#- name: Set permissions on socket - mode
#  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"
#  notify: restart php5-fpm

- name: Install php.ini
  become: yes
  template: src=php.ini.tpl dest=/etc/php/7.2/fpm/php.ini
  notify: restart php7.2-fpm

- name: ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php/7.2/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'
