---
- name: Install Nginx
  become: yes
  apt: pkg=nginx state=latest

- name: Change default nginx site
  become: yes
  template: src={{ ws_template }} dest={{ ws_vhost_path }}/{{ ws_vhost_file }}
  notify: restart nginx
