---
- hosts:
    - all
  sudo: true
  vars:
    servername: adloginpoc.vb adloginpoc 192.168.33.99
    appdir: /var/www/adloginpoc
    hostname: adloginpoc
  vars_files:
    - vars/pgsql.yml
    - vars/common.yml
    - vars/app.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php7.2-cli
    - nginx
    - php7.2-fpm
    - pgsql
    - composer
    - phpcommon
    - dev
    - xdebug
#    - app
